project:
  type: website
  preview: 
    port: 8199 
    watch-inputs: true
    browser: false
  

website:
  title: "HSI Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 2025-2026/index.qmd
        text: "HSI 2025-2026"
  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    email-obfuscation: javascript

metadata-files:
  - ./navigation/_sidebars.yml

