---
title: "HSI Handbook & HSIP"
description: "Class on the HSI Handbook and Human Systems Integration Plans (HSIP)."
authors: ["D. Masson", "A. Disdier"]
date: 2026-01-05
duration: "2h"
type: class
---

# HSI Handbook & HSIP

## Synopsis

This session introduces the core principles of HSI through the lens of the NASA HSI Handbook (2021). The idea is to provide an overview of the different HSI Domains and motivate through real-life aerospace case studies how HSI can improve system performance while reducing costs and risks.

## Session Objectives

Get an overview of HSI principles from the point of view of NASA.

## Key Concepts

- HSI Handbook
- HSI Plan

## In-Class Activities

<style>
.slide-deck {
    border: 3px solid #dee2e6;
    width: 100%;
    height: 475px;
}
</style>

<div>
```{=html}
<iframe class="slide-deck" src="hsi-handbook-hsip-slides.html"></iframe>
```
</div>

## Preparation & Readings
**Before project session on Wednesday**:
- Fetch the PDF file of the Handbook at [https://ntrs.nasa.gov/citations/20210010952](https://ntrs.nasa.gov/citations/20210010952) and **read Sections 2.1 and 2.3** (you can skim Section 2.2 about HSI Domains for now and refer to it later)
- Take a look at [the HSI Plan (student-friendly version)](assets/hsi-plan.docx) that you will need to fill in for the evaluation

## Notes
